# Generated by Django 3.2.3 on 2021-06-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210622_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='initurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='short',
            name='shortenurl',
            field=models.CharField(default='', max_length=10),
        ),
    ]
