# Generated by Django 3.2.3 on 2021-06-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210622_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='initurl',
            field=models.CharField(max_length=500),
        ),
    ]
