# Generated by Django 3.2.3 on 2021-06-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_short_initurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
